### ISSUE TITLE
About train.h5 and valid.h5

### ISSUE THREAD

**Issue by GilgameshD** [geopavlakos/object3d#1]
Thanks for making such an outstanding job, and I have already ran the project on my PC. 
	
But I notice that the train and validation files (HDF5) is directly downloaded from the website, and the content of them is different from those files from /PASCAL3D/Annotation. I think that some transform process should be done between these two kinds of file, but I couldn't find it. So would you mind telling me how can I get those .h5 files for training and validating this CNN from my own dataset?

**Comment by geopavlakos** [comment]
The original annotations of PASCAL3D have been transformed to be compatible with the Stacked Hourglass network code. If you want to train on your own dataset, you need to define the annotations for the bounding box of the object ('center' and 'scale'), as well as the keypoint locations on the image ('part'). Please take a look at the file demoCustom.m, where an example for testing on custom images is presented. You can follow the code to similarly create train.h5 and valid.h5 for your own data.

**Comment by GilgameshD** [comment]
Thanks a lot.

**Comment by meijieru** [comment]
As from the paper, it was trained on all classes with 124 keypoints, while in the h5 files provided, there are only 102 keypoints?
Could you provide the code for preprocessing for more details about it?
Thanks a lot.
